package awem.autotests.tests;

import awem.autotests.helpers.DriverUtils;
import awem.autotests.steps.StepsTests;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Configuration.baseUrl;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class TestsUI extends TestBase {

    @Test
    @DisplayName("Проверка заголовка")
    void checkingTitle() {
        new StepsTests()
                .CheckingTitleAwem();
    }

    @Test
    @DisplayName("Проверка смены языка на англ")
    void languageChange() {
        new StepsTests()
                .lang()
                .CheckingLanguageChange();
    }

    @Test
    @DisplayName("Проверка наличия игры Cradle of Empires по влкаде Игры")
    void presenceOfTheGame() {
        new StepsTests()
                .thePresenceOfTheGame()
                .CheckingNeedGame();
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://awem.com/'", () ->
                open("https://awem.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }

    @Test
    void job() {
        open(baseUrl);
        $x("//*[@href='https://awem.com/careers/']").click();
        $x("//*[@href='https://awem.com/careers/qa/']").click();
        $x("//*[text()='QA']").scrollTo();
        $x("//*[@href='https://awem.com/vacancy/middle-software-testing-engineer/']").click();
        $x("//*[@class='btn js-popup-open btn--vacancy-intro']").click();
//        $x("//*[text() = 'Cradle of Empires']").shouldBe(Condition.visible);
    }


}